"""
organizer.py
------------
Core file-organizing logic for File Organizer v2.0.

Provides two top-level operations:
  scan_folder()     → analyze without moving (Preview / Analyze mode)
  organize_folder() → actually move files (with callbacks for UI progress)

Preserves all behaviour from the original file_organizer.py v1 while adding:
  - Recursive folder scanning
  - SHA-256 duplicate detection
  - Per-file duplicate resolution callbacks
  - Skipping organizer-owned folders
  - Structured logging via logger.py
  - Undo recording via undo_manager.py
"""

import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Dict, List, Optional

import categories
import duplicate_detector
import logger as log_module
import undo_manager as undo_module
import config_manager

# Files generated by the organizer itself — never move these
ORGANIZER_OWNED_FILES = {"log.txt", "organizer_log.jsonl", "report.txt"}


# ── Data structures ───────────────────────────────────────────────────────────

@dataclass
class FilePreview:
    """Describes what will happen to a single file in Preview mode."""
    filename: str
    source_path: Path
    destination_category: str   # e.g. "Images"
    destination_path: Path
    is_name_conflict: bool
    is_content_duplicate: bool
    file_size: int = 0


@dataclass
class PreviewResult:
    """Aggregate result of a scan_folder() call."""
    total_files: int = 0
    organizable: int = 0
    going_to_others: int = 0
    name_conflicts: int = 0
    content_duplicates: int = 0
    total_size: int = 0
    file_previews: List[FilePreview] = field(default_factory=list)
    category_counts: Dict[str, int] = field(default_factory=dict)
    category_sizes: Dict[str, int] = field(default_factory=dict)


@dataclass
class OrganizeResult:
    """Aggregate result of an organize_folder() call."""
    total_files: int = 0
    moved: int = 0
    skipped: int = 0
    errors: int = 0
    total_size: int = 0
    category_stats: Dict[str, int] = field(default_factory=dict)
    category_sizes: Dict[str, int] = field(default_factory=dict)
    error_messages: List[str] = field(default_factory=list)


# ── DuplicateAction enum ──────────────────────────────────────────────────────

class DuplicateAction:
    SKIP = "skip"
    KEEP_BOTH = "keep_both"
    REPLACE = "replace"


# ── Helpers ───────────────────────────────────────────────────────────────────

def _collect_files(folder: Path, recursive: bool,
                   skip_dirs: set[str]) -> List[Path]:
    """
    Collect all files to be organized.
    Skips:
      - Organizer-owned subdirectories (Images, PDFs, etc.)
      - Organizer-generated files (log.txt, report.txt, organizer_log.jsonl)
    """
    files: List[Path] = []

    if recursive:
        for item in folder.rglob("*"):
            # Skip any path whose top-level parent is an organizer folder
            relative = item.relative_to(folder)
            parts = relative.parts
            if len(parts) > 0 and parts[0] in skip_dirs:
                continue
            if item.is_file() and item.name not in ORGANIZER_OWNED_FILES:
                files.append(item)
    else:
        for item in folder.iterdir():
            if item.is_file() and item.name not in ORGANIZER_OWNED_FILES:
                files.append(item)

    return files


# ── Public API ────────────────────────────────────────────────────────────────

def scan_folder(
    folder_path: str | Path,
    recursive: bool = False,
) -> PreviewResult:
    """
    Scan a folder and return a preview of what would happen — NO files are moved.

    Args:
        folder_path: Directory to organize.
        recursive:   Include subdirectories.

    Returns:
        PreviewResult with per-file and aggregate information.
    """
    folder = Path(folder_path)
    cats = categories.get_categories()
    skip_dirs = set(categories.ORGANIZER_FOLDERS)

    result = PreviewResult()
    result.category_counts = {cat: 0 for cat in cats}
    result.category_counts["Others"] = 0
    result.category_sizes = {cat: 0 for cat in cats}
    result.category_sizes["Others"] = 0

    files = _collect_files(folder, recursive, skip_dirs)
    result.total_files = len(files)

    for file_path in files:
        ext = file_path.suffix.lower()
        cat = categories.get_category_for_file(file_path.name, ext, cats)
        dest_dir = folder / cat
        dest_path = dest_dir / file_path.name
        
        try:
            size = file_path.stat().st_size
        except OSError:
            size = 0

        dup_info = duplicate_detector.check_duplicate(file_path, dest_path)

        preview = FilePreview(
            filename=file_path.name,
            source_path=file_path,
            destination_category=cat,
            destination_path=dest_path,
            is_name_conflict=dup_info.name_conflict,
            is_content_duplicate=dup_info.content_duplicate,
            file_size=size,
        )

        result.file_previews.append(preview)
        result.organizable += 1
        result.total_size += size

        if cat == "Others":
            result.going_to_others += 1
        if dup_info.name_conflict:
            result.name_conflicts += 1
        if dup_info.content_duplicate:
            result.content_duplicates += 1

        result.category_counts[cat] = result.category_counts.get(cat, 0) + 1
        result.category_sizes[cat] = result.category_sizes.get(cat, 0) + size

    return result


def organize_folder(
    folder_path: str | Path,
    recursive: bool = False,
    on_progress: Optional[Callable[[str, str, int, int], None]] = None,
    on_duplicate: Optional[Callable[[FilePreview, duplicate_detector.DuplicateInfo],
                                    str]] = None,
    undo_mgr: Optional[undo_module.UndoManager] = None,
) -> OrganizeResult:
    """
    Organize files in a folder by moving them into category subfolders.

    Args:
        folder_path:  Directory to organize.
        recursive:    Include subdirectories.
        on_progress:  Callback(filename, category, current_index, total) — for UI.
        on_duplicate: Callback(FilePreview, DuplicateInfo) → DuplicateAction string.
                      If None, defaults to KEEP_BOTH (safe auto-rename).
        undo_mgr:     UndoManager instance for recording moves.

    Returns:
        OrganizeResult with statistics and any error messages.
    """
    folder = Path(folder_path)
    cats = categories.get_categories()
    skip_dirs = set(categories.ORGANIZER_FOLDERS)

    org_logger = log_module.OrganizerLogger(folder)
    org_logger.open_session()

    if undo_mgr:
        undo_mgr.start_session(str(folder))

    result = OrganizeResult()
    result.category_stats = {cat: 0 for cat in cats}
    result.category_stats["Others"] = 0
    result.category_sizes = {cat: 0 for cat in cats}
    result.category_sizes["Others"] = 0

    files = _collect_files(folder, recursive, skip_dirs)
    result.total_files = len(files)

    global_dup_action = config_manager.get("duplicate_action", "keep_both")

    for idx, file_path in enumerate(files, start=1):
        filename = file_path.name
        ext = file_path.suffix.lower()
        cat = categories.get_category_for_file(filename, ext, cats)
        
        try:
            size = file_path.stat().st_size
        except OSError:
            size = 0

        dest_dir = folder / cat
        dest_dir.mkdir(parents=True, exist_ok=True)
        dest_path = dest_dir / filename

        # Notify UI
        if on_progress:
            on_progress(filename, cat, idx, result.total_files)

        # ── Duplicate resolution ───────────────────────────────────────────
        dup_info = duplicate_detector.check_duplicate(file_path, dest_path)

        if dup_info.name_conflict:
            action = DuplicateAction.KEEP_BOTH  # safe default

            if global_dup_action == "ask" and on_duplicate:
                preview = FilePreview(
                    filename=filename,
                    source_path=file_path,
                    destination_category=cat,
                    destination_path=dest_path,
                    is_name_conflict=dup_info.name_conflict,
                    is_content_duplicate=dup_info.content_duplicate,
                    file_size=size,
                )
                action = on_duplicate(preview, dup_info)
            else:
                if global_dup_action == "skip":
                    action = DuplicateAction.SKIP
                elif global_dup_action == "keep_both":
                    action = DuplicateAction.KEEP_BOTH
                elif global_dup_action == "replace":
                    action = DuplicateAction.REPLACE

            if action == DuplicateAction.SKIP:
                entry = log_module.LogEntry(
                    filename=filename,
                    original_path=str(file_path),
                    new_path=None,
                    action="SKIPPED",
                    status="SKIPPED",
                )
                org_logger.log(entry)
                result.skipped += 1
                continue

            elif action == DuplicateAction.KEEP_BOTH:
                # Auto-rename to avoid conflict
                dest_path = duplicate_detector.get_unique_filename(dest_path)

            elif action == DuplicateAction.REPLACE:
                # User explicitly confirmed replacement
                pass  # dest_path stays as-is; shutil.move will overwrite

        # ── Move file ─────────────────────────────────────────────────────
        try:
            shutil.move(str(file_path), str(dest_path))

            entry = log_module.LogEntry(
                filename=filename,
                original_path=str(file_path),
                new_path=str(dest_path),
                action="MOVED",
                status="SUCCESS",
            )
            org_logger.log(entry)

            if undo_mgr:
                undo_mgr.record_move(file_path, dest_path)

            result.moved += 1
            result.total_size += size
            result.category_stats[cat] = result.category_stats.get(cat, 0) + 1
            result.category_sizes[cat] = result.category_sizes.get(cat, 0) + size

        except PermissionError as e:
            msg = f"Permission denied: {filename}"
            result.errors += 1
            result.error_messages.append(msg)
            org_logger.log(log_module.LogEntry(
                filename=filename,
                original_path=str(file_path),
                new_path=None,
                action="ERROR",
                status="FAILED",
                error_message=str(e),
            ))

        except FileNotFoundError as e:
            msg = f"File not found (may have been moved): {filename}"
            result.errors += 1
            result.error_messages.append(msg)
            org_logger.log(log_module.LogEntry(
                filename=filename,
                original_path=str(file_path),
                new_path=None,
                action="ERROR",
                status="FAILED",
                error_message=str(e),
            ))

        except OSError as e:
            msg = f"Error moving {filename}: {e}"
            result.errors += 1
            result.error_messages.append(msg)
            org_logger.log(log_module.LogEntry(
                filename=filename,
                original_path=str(file_path),
                new_path=None,
                action="ERROR",
                status="FAILED",
                error_message=str(e),
            ))

    # ── Finalize ──────────────────────────────────────────────────────────────
    org_logger.log_session_summary(
        total=result.total_files,
        moved=result.moved,
        errors=result.errors,
        skipped=result.skipped,
    )
    org_logger.write_report(result.category_stats, result.moved)
    org_logger.close_session()

    if undo_mgr:
        undo_mgr.commit_session(errors=result.errors, duplicates=result.skipped, skipped=result.skipped)

    return result
